services:

  frontend:
    image: ghcr.io/YOUR_USER/frontend:latest
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - front-tier

  backend:
    image: ghcr.io/YOUR_USER/backend:latest
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - front-tier
      - back-tier
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier
    restart: unless-stopped

networks:
  front-tier:
  back-tier:
