sonar.projectKey=Task-App-Test
sonar.projectName=Task App Test
sonar.sourceEncoding=UTF-8

sonar.sources=trainingAppBackend,trainingFronend/src

sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/coverage/**,**/.git/**
