apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend
      harness.io/track: stable

  template:
    metadata:
      labels:
        app: frontend
        harness.io/track: stable

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: frontend
          image: <+artifacts.primary.image>
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend

spec:
  selector:
    app: frontend

  ports:
    - port: 3001
      targetPort: 80

  type: ClusterIP
