sonar.projectKey=Task-App-Frontend
sonar.projectName=Task App Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.exclusions=\
**/node_modules/**,\
**/build/**,\
**/dist/**,\
**/coverage/**,\
**/*.test.js,\
**/*.test.jsx,\
**/*.spec.js,\
**/*.spec.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
