name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.USER_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest ./trainingAppBackend
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest ./trainingFronend
          docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/obadh
            docker compose pull
            docker compose up -d
